#!/bin/bash


# Creates symbolic links from config files

# The first argument is the original file,
# the second is the link

# In the event a file already exists
# at the desired link location, the user
# will be prompted to overwrite


# Absolute path to repo
DIR="$(dirname "$(readlink -f "$0")")"

# i3
ln --symbolic --interactive ${DIR}/.config/i3/config ~/.config/i3/config

# .bashrc
ln --symbolic --interactive ${DIR}/.bashrc ~/.bashrc
