#!/bin/bash


# Creates hard links from config files

# The first argument is the original file,
# the second is the hard link

# This will OVERWRITE any existing config files
# in ~/ at the paths specified below with the versions
# contained in this repo


# i3
ln -f .config/i3/config ~/.config/i3/config
