#!/bin/bash


# Creates symbolic links from config files

# The first argument is the original file,
# the second is the link

# In the event a file already exists
# at the desired link location, the user
# will be prompted to overwrite


# Absolute path to repo
REPO_DIR="$(dirname "$(readlink -f "$0")")"

# Paths relative to ~/
FILES=(

    ######
    # i3 #
    ######
    '.config/i3/config'

    ########
    # bash #
    ########
    '.bashrc'

    ##############
    # Xresources #
    ##############
    '.Xresources'

)

for FILE in "${FILES[@]}"
do
    ln --symbolic --interactive "$REPO_DIR/$FILE" "$HOME/$FILE"
done
